# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json
name: art-voice-agent-accelerator
metadata:
  template: azd-init@1.15.1

infra:
  provider: bicep
  path: ./infra

services:
  rtaudio-client:
    project: apps/rtagent/frontend
    host: containerapp
    language: js
    docker:
      path: ./Dockerfile
      context: .
      platform: linux/amd64
      
  rtaudio-server:
    project: apps/rtagent/backend
    host: containerapp
    language: python
    docker:
      path: ./Dockerfile
      context: ../../../
      platform: linux/amd64

hooks:
  preprovision:
    shell: sh
    run: ./devops/scripts/azd-preprovision.sh
    interactive: true
    continueOnError: false
  postprovision:
    shell: sh
    run: ./devops/scripts/azd-postprovision.sh
    interactive: true
    continueOnError: false